### ISSUE TITLE
Deploy to Heroku with data - RATED 3

### ISSUE THREAD

**Issue by rxtATX** [rxtATX/OffNOn#135]
The application must be deployed to heroku.
Remember, when you run the "heroku create" command, you can optionally pass "-a" and then supply a specific application name
This deployment will resemble submitting unit 14's homework assignment
You will need to provision a JawsDB instance
You will need to update the config vars to include any secret keys from the .env file.

**Comment by codeDevLogan** [comment]
https://limitless-castle-65696.herokuapp.com/
