### ISSUE TITLE
Models and Connection - RATED 5

### ISSUE THREAD

**Issue by rxtATX** [rxtATX/OffNOn#3]
We'll need to add connection.js to the config folder, its contents should be able to dynamically and locally connect to sequelize.
- config
    - connection.js

models folder should have an index file and 3 model files
- models
    - index.js
    - User.js
    - Ticket.js
    - Logs

db folder should have a schema.sql file
  
Acceptance Criteria: The folder structure should be present with all mentioned files. The content of these files: connection.js should be good to go to use .env to connect to local. Models folder each of the model files should have the "class extends" syntax, init function, and module.exports syntax - init description can be accomplished in another card.

**Comment by Christoph551** [comment]
Added model structure for index, log, ticket and user.js files. Also added db/schema.sql file.  
Additionally, I opted to set up the .env file with the credentials for connection.js.

**Comment by Christoph551** [comment]
Changed user_id in ticket model to client_id and added a tech_id with 
the same references as client_id. Got rid of user_name from the User model. Added hidden boolean in the Log model.
