### ISSUE TITLE
Utils folder Handlebars Helpers - RATED 6

### ISSUE THREAD

**Issue by rxtATX** [rxtATX/OffNOn#31]
The developer will be creating a renderUrgencyChip function for use by the handlebars template files.

Acceptance criteria:
- [x] It is done when the server is confirmed to be importing the "helpers.js" file.
- [x] It is done when the helpers are confirmed to be passed as an argument to the handelbars.create({}) option object.
- [x] It is done when the utils folder is confirmed to exist.
- [x] It is done when the helpers.js file is confirmed to exist inside the utils folder.
- [x] It is done when inside the helpers file, an object is added to the module.exports.
- [x] It is done when on this object, a function called renderUrgencyChip is defined.
- [x] It is done when this function takes in an "urgency" argument.
- [x] It is done when this function runs a switch case to compare the urgency value to these options: Low, Medium, High, Critical
    - The result of these cases should render a chip as shown in Figure 1.
    - The color of the background will depend on the urgency.
    - The color of the font will reflect either black or white, whichever has highest contrast with the background color.
- [x] It is done when an HTML-like string is returned out of this function.

Figure 1.
![Image](https://user-images.githubusercontent.com/20586946/217938318-73c0b395-bf05-42f5-913f-cd5e2b70ddf4.png)

**Comment by rxtATX** [comment]
NOT CRITICAL?

**Comment by rxtATX** [comment]
GREY, YELLOW, RED

**Comment by codeDevLogan** [comment]
This should be finished.
