### ISSUE TITLE
Controllers for ApiRoutes - RATED 4

### ISSUE THREAD

**Issue by rxtATX** [rxtATX/OffNOn#5]
We'll need an apiRoutes folder with an index file, and one file for each model.

- apiRoutes /
    - index.js
    - userRoutes.js
    - ticketRoutes.js
    - logRoutes.js
  
Acceptance Criteria: The folder structure needs to match this outline. The content of the files should have the Router initialized and exported. index.js file should allow for routes that "continue" with the matching filename example: "/user", "/log"
The userRoutes.js file should match the content of in-class activity 14 > 24

Additionally pseudo-code (as comment) which of the Api from routes table belongs in each file.

**Comment by codeDevLogan** [comment]
Working on it now.
